sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t mbhein/include-beer-app .
# test image
- docker run mbhein/include-beer-app --version
